# Generated by Django 3.1 on 2020-09-14 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200913_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom',
            new_name='intitule',
        ),
    ]
