# Generated by Django 3.1 on 2020-09-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200914_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='intitule',
            new_name='nom',
        ),
    ]
