# Generated by Django 3.1 on 2020-09-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200914_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('addresse', models.TextField()),
                ('photo', models.ImageField(upload_to='Templates/blog/Media/')),
            ],
        ),
    ]
