# Generated by Django 3.1 on 2020-09-24 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[(' à la livraison', ' à la livraison'), ('Mobile money', 'Mobile money'), ('paypal', 'paypal'), ('carte de crédit', 'carte de crédit'), ('Bitcoin', 'Bitcoin')], db_index=True, max_length=150, verbose_name='paiement')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mode De Paiement',
                'verbose_name_plural': 'Modes De Paiements',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tel', models.CharField(max_length=150)),
                ('tel2', models.CharField(blank=True, help_text='numéro optinelle', max_length=150)),
                ('livraison', models.CharField(choices=[('à domicile : par nawa delivery ', 'à domicile : Par nawa delivery'), ('à domicile : par le vendeur', ' à domicile : par le vendeur'), ('pas besoin de livraison', 'pas besoin de livraison')], db_index=True, default='à domicile : Par nawa delivery', max_length=100)),
                ('quartier', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('total', models.IntegerField(default=0, verbose_name='prix total de la commande')),
                ('reduct', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='prix total de réduction')),
                ('payement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Mode_Payement', to='Mes_commandes.mode_payement', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=150, unique=True, verbose_name='ville')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=150, unique=True, verbose_name='ville')),
                ('zone', models.CharField(choices=[('zone 1', ' zone 1'), ('zone 2', ' zone 2'), ('zone 3', ' zone 3')], db_index=True, default='zone 1', max_length=150)),
                ('prix_livraison', models.IntegerField(default=0)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mes_commandes.ville')),
            ],
            options={
                'verbose_name': 'Quartier',
                'verbose_name_plural': 'Quartiers',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=10)),
                ('nom', models.CharField(default='', max_length=100)),
                ('vendeur', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('confirmer', models.BooleanField(default=False)),
                ('payer', models.BooleanField(default=False)),
                ('annuler', models.BooleanField(default=False)),
                ('confier_votre', models.BooleanField(default=False, help_text='confier votre liraison à bekeymarkets', verbose_name='confier votre liraison')),
                ('prix_livraison', models.IntegerField(default=0, help_text="Laisser vide temps que la commande n'est pas payer ", verbose_name='prix de la livraison')),
                ('livraison_day', models.DateTimeField(blank=True, help_text="Laisser vide temps que la commande n'est pas payer ", null=True, verbose_name='Jour de livraison de la commande ')),
                ('total', models.IntegerField(default=0, verbose_name='prix total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Mes_commandes.order')),
            ],
            options={
                'verbose_name': 'Produit De La Commande',
                'verbose_name_plural': 'Produits De La Commande',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='Mes_commandes.ville'),
        ),
    ]
