# Generated by Django 3.1 on 2020-09-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mes_commandes', '0002_auto_20200924_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
